# This is the actual configuration file for litestream.
#
# You can either use the generated `config/initializers/litestream.rb`
# file to configure the litestream-ruby gem, which will populate these
# ENV variables when using the `rails litestream:replicate` command.
#
# Or, if you prefer, manually manage ENV variables and this configuration file.
# In that case, simply ensure that the ENV variables are set before running the
# `replicate` command.
#
# For more details, see: https://litestream.io/reference/config/
dbs:
  - path: storage/production.sqlite3
    replicas:
      - type: s3
        bucket: <%= Rails.configuration.litestream.replica_bucket %>
        path: storage/production.sqlite3
        access-key-id: <%= Rails.configuration.litestream.replica_key_id %>
        secret-access-key: <%= Rails.configuration.litestream.replica_access_key %>
  - path: storage/production_cache.sqlite3
    replicas:
      - type: s3
        bucket: <%= Rails.configuration.litestream.replica_bucket %>
        path: storage/production_cache.sqlite3
        access-key-id: <%= Rails.configuration.litestream.replica_key_id %>
        secret-access-key: <%= Rails.configuration.litestream.replica_access_key %>
  - path: storage/production_queue.sqlite3
    replicas:
      - type: s3
        bucket: <%= Rails.configuration.litestream.replica_bucket %>
        path: storage/production_queue.sqlite3
        access-key-id: <%= Rails.configuration.litestream.replica_key_id %>
        secret-access-key: <%= Rails.configuration.litestream.replica_access_key %>
  - path: storage/production_cable.sqlite3
    replicas:
      - type: s3
        bucket: <%= Rails.configuration.litestream.replica_bucket %>
        path: storage/production_cable.sqlite3
        access-key-id: <%= Rails.configuration.litestream.replica_key_id %>
        secret-access-key: <%= Rails.configuration.litestream.replica_access_key %>
